package by.toxa.fishingshop.command;

public enum CommandType {
    GO_TO_START_PAGE_COMMAND,
    GO_TO_USERS_PAGE_COMMAND,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_SIGN_UP_PAGE_COMMAND,
    GO_TO_ADD_NEW_PRODUCT_PAGE_COMMAND,
    DEFAULT,
    START_PAGE_COMMAND,
    LOGIN_PAGE_COMMAND;


}
